[package]
name = "gsr"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
image = "0.25.1"
palette_extract = "0.1.0"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
walkdir = "2.5.0"
